# Generated by Django 5.2.4 on 2025-09-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='image',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to='images/'),
        ),
    ]
